services:
  - type: web
    name: mood-index-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DB_USER
        value: postgres
      - key: DB_HOST
        value: moodindex-db.ci56kq0wsfa0.us-east-1.rds.amazonaws.com
      - key: DB_NAME
        value: moodindex
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 5432
      - key: JWT_SECRET
        sync: false
